os: osx
osx_image: xcode11.6
language: swift
scirpt: xcodebuild clean build test -workspace "ScrabWordFinder.xcworkspace"  -scheme "ScrabWordFinder" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.6,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO